### ISSUE TITLE
About bf16

### ISSUE THREAD

**Issue by Doctor-James** [hp-l33/AiM#10]
I found that although you set bf16=True in TrainingArguments, it seems the entire model is still being trained in fp32. Have you checked this? Then when I forcibly put the entire model in bf16, the loss decreases much more slowly. By the way, I use RTX4090.
Here is my code, I made some modifications.
```
def compute_loss(self,):
.....
    dtype = torch.bfloat16 if self.args.bf16 else torch.float32
    if model.get_projector_weight_dtype() != dtype:
         model = model.to(dtype=dtype)
         x = x.to(dtype=dtype)
```
bf16: bz=128x8 lr=4e-4
fp32: bz=64x8 lr=2e-4

**Comment by hp-l33** [comment]
When setting bf16, the model weights are stored in bf16, while gradients (computed in half-precision and then converted to full precision for updates) and optimizer states are still processed in full 32-bit precision.
