### ISSUE TITLE
bad result

### ISSUE THREAD

**Issue by Doctor-James** [hp-l33/AiM#12]
Hello, could you provide a script for reproducing the FID? I am using the pytorch-fid library to calculate it with AiM-B, topk=600, topp=0.98, and cfg=5, and the FID score is 9.3, which is significantly different from the value in the paper.

Here is part of my code

`

    all_classes = list(range(args.num_classes)) * (args.num_fid_samples // args.num_classes)
    subset_len = len(all_classes) // dist.get_world_size()
    all_classes = np.array(all_classes[rank * subset_len: (rank+1)*subset_len], dtype=np.int64)
    cur_idx = 0

    for _ in pbar:
        # Sample inputs:
        # c_indices = torch.randint(0, args.num_classes, (n,), device=device)
        y = torch.from_numpy(all_classes[cur_idx * n: (cur_idx+1)*n]).to(device)
        cur_idx += 1
        with torch.inference_mode():
            images = model.generate(c=y,batch=len(y), temperature=1, top_p=0.98, top_k=600, cfg_scale=5)
        images = images * 0.5 + 0.5
        images = torch.clamp(255 * images, 0, 255).permute(0, 2, 3, 1).to("cpu", dtype=torch.uint8).numpy()
        # Save samples to disk as individual .png files
        for i, sample in enumerate(images):
            index = i * dist.get_world_size() + rank + total
            Image.fromarray(sample).save(f"{sample_folder_dir}/{index:06d}.png")
        total += global_batch_size
`

By the way, I notice that the adaln_group for AiM_B is False in your code, but in paper, the Groups for AiM_B is 24.

**Comment by hp-l33** [comment]
Hi,

We used the same evaluation script as [LLamaGen](https://github.com/FoundationVision/LlamaGen/tree/main/evaluations/c2i), with the following parameter settings: `temperature=1, top_p=1.0, top_k=0, cfg_scale=1.75 or 2.0`

The reason for the difference in parameter settings when evaluating FID compared to those provided in the README is that higher cfg-scale and certain top-k parameters can improve visual quality but are not conducive to accurate FID evaluation.

For more details, please refer to: https://github.com/FoundationVision/VAR?tab=readme-ov-file#sampling--zero-shot-inference

**Comment by hp-l33** [comment]
Apologies for the lack of a clear explanation in the README. It will be updated shortly with the appropriate parameter settings for evaluation.

**Comment by Doctor-James** [comment]
Thank you for your timely reply, looking forward to the update of the code
