### ISSUE TITLE
How to run it completely on cpu?

### ISSUE THREAD

**Issue by Meshwa428** [hp-l33/AiM#2]
I tried changing the device to cpu in your colab notebook, but it throws

CUDA errors

Can you please guide me 🙏🏼

**Comment by hp-l33** [comment]
Hi, as far as I know, the `causal_conv1d` used in Mamba does not currently support CPU inference. You might want to check the issues in the Mamba original repository to see if there's any related solution. I'm really sorry that I can't help you with this.
