### ISSUE TITLE
Positional Encoding

### ISSUE THREAD

**Issue by Bezdarnost** [hp-l33/AiM#4]
Thank you very much for your work!

Where can I find more details about your implementation of positional encoding in the model?

**Comment by hp-l33** [comment]
Hi, the positional encoding can be found within `GPT2Embeddings` located in `models/stage2/mixer_seq_simple.py`. By the way, the official implementation of mamba actually reserves an interface for positional encoding, though it is not utilized. For the implementation of  positional encoding during the inference phase, you can refer to the relevant code in `models/stage2/generation.py`.
