### ISSUE TITLE
How to Merge weights?

### ISSUE THREAD

**Issue by txchen-USTC** [hp-l33/AiM#9]
I have finished my stage 2 training and got optimizer.pt, pytorch_model.bin. I notice that your provided weights are all .safetensors weights. Could you provide some details on how to merge the stage 2 weight with the stage 1 vq_f16.pt to get the final safetensor weight? Also, it seems that the config.json will not be generated after stage 2 training, any way to generate this? Many thanks!

**Comment by hp-l33** [comment]
Hi, we use HuggingFace's integration tools to merge the weights of stage 1 and stage 2 and generate the config.json. Please refer to the code for details.
``` python
from aim import AiM

# load model
model = AiM()

# equip with weights
model.vqvae.load_state_dict(...)
model.mamba.load_state_dict(...)

# push to hub
model.push_to_hub("your-hf-organzation-or-username/aim-base")

# reload
model = AiM.from_pretrained("your-hf-organzation-or-username/aim-base")
```
